In [1]:
import pandas as pd
df=pd.read_csv("/home/jash/Desktop/petplan/Profitability1.txt", sep='\t', lineterminator='\n')

In [2]:
df.iloc[267910][0]

'.00000000000000000|30|CAN130603Atlantis|2015-06-23|2015-07-22|19471||.000000|Border Collie Mix|4|.80|100|Dog|Introductory|AGR|||||||130603|CAN|(306) 221-8268|Hamp|Mckenzie|24-1001 12th st e|saskatoon|SK|S7L 0C9|LowTenure-LowLR||1\r'

In [3]:
df.iloc[267909][0]

'|116|CAN362374Churchill|2018-04-03|2019-04-02|147830||103.751671|Pembroke Welsh Corgi|2|.80|500|Dog|5000|CAN|||||||362374|CAN|(604) 728-7598|Rafati|Nima|#70-250 E. 15th St.|North Vancouver|BC|V7L 2R4|LowTenure-LowLR||0\r'

In [4]:
df.iloc[299539][0]

'|200|US2204538Bella|2018-01-09|2019-01-08|585904||118.367123|Mixed Breed Small ( up to 22lb )|2|.80|500|Dog|10000|XLC|||||||2204538|US|(215) 378-6330|Gordon|Diane|13 Hillside Ln|Yardley|PA|19067-5403|LowTenure-LowLR||0\r'

In [5]:
a=pd.read_table("/home/jash/Desktop/petplan/Profitability1.txt", sep='|', lineterminator='\n', error_bad_lines=False)

Skipping line 267909: expected 33 fields, saw 34

Skipping line 299539: expected 33 fields, saw 34

/home/jash/anaconda3/envs/py27/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (5,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
a.head()

,LossRatio,Duration,PetId,StartDate,EndDate,LastPolicyRef,TotalClaimsAmtPaid,TotalEarnedPremium,BreedName,Currentage,...,PhoneNumber,Surname,GivenName,CustomerMailingAddr_Addr1,CustomerMailingAddr_City,CustomerMailingAddr_StateProvCd,CustomerMailingAddr_PostalCode,Quadrant,claimdurationInception,churn
0,0.618038,1026,US1439036kayla,2015-10-06,2018-11-24,560481,1319.141,2134.399452,Mixed Breed Medium (23 - 70lb),9.0,...,(862) 252-4483,algarin,jason,684 Dorothea Ln,Elmont,NY,11003-4520,HighTenure-HighLR,952.0,0
1,12.842839,484,US1960128Corbie,2017-03-31,2019-03-30,608993,7568.184,589.292137,Dachshund - long haired,4.0,...,(770) 870-7404,Gardener,Jessica,6902 E Taos Pl,Tucson,AZ,85715-3343,HighTenure-HighLR,255.0,0
2,0.058918,1025,US1332798Sophie,2015-06-20,2018-04-09,454361,58.460,992.219616,Mixed Breed Small ( up to 22lb ),2.0,...,(818) 262-0387,Auster,Allyson,2151 Calle Lys,Thousand Oaks,CA,91360-4933,HighTenure-LowLR,921.0,1
3,16.312924,528,US1437703Siggy,2015-10-05,2017-03-15,289557,9040.553,554.195726,Labrador Mix,6.0,...,(512) 289-7915,Morgan,Yanin,2036 Columbia St,Houston,TX,77008-2637,LowTenure-HighLR,401.0,1
4,8.421790,1080,US150902Dino,2015-08-13,2018-08-12,508838,12328.316,1463.859397,Mixed Breed Medium (23 - 70lb),3.0,...,(850) 368-7632,Hawkey,Melanie,7142 East Bay Blvd,Navarre,FL,32566-9013,HighTenure-HighLR,341.0,0

In [7]:
data=pd.DataFrame(data=a,index=None)

In [8]:
data.shape

(425903, 33)

In [9]:
data['L']=0

In [10]:
data.loc[data['LossRatio'] >.57, 'L'] = 1

In [11]:
data.head()

,LossRatio,Duration,PetId,StartDate,EndDate,LastPolicyRef,TotalClaimsAmtPaid,TotalEarnedPremium,BreedName,Currentage,...,Surname,GivenName,CustomerMailingAddr_Addr1,CustomerMailingAddr_City,CustomerMailingAddr_StateProvCd,CustomerMailingAddr_PostalCode,Quadrant,claimdurationInception,churn,L
0,0.618038,1026,US1439036kayla,2015-10-06,2018-11-24,560481,1319.141,2134.399452,Mixed Breed Medium (23 - 70lb),9.0,...,algarin,jason,684 Dorothea Ln,Elmont,NY,11003-4520,HighTenure-HighLR,952.0,0,1
1,12.842839,484,US1960128Corbie,2017-03-31,2019-03-30,608993,7568.184,589.292137,Dachshund - long haired,4.0,...,Gardener,Jessica,6902 E Taos Pl,Tucson,AZ,85715-3343,HighTenure-HighLR,255.0,0,1
2,0.058918,1025,US1332798Sophie,2015-06-20,2018-04-09,454361,58.460,992.219616,Mixed Breed Small ( up to 22lb ),2.0,...,Auster,Allyson,2151 Calle Lys,Thousand Oaks,CA,91360-4933,HighTenure-LowLR,921.0,1,0
3,16.312924,528,US1437703Siggy,2015-10-05,2017-03-15,289557,9040.553,554.195726,Labrador Mix,6.0,...,Morgan,Yanin,2036 Columbia St,Houston,TX,77008-2637,LowTenure-HighLR,401.0,1,1
4,8.421790,1080,US150902Dino,2015-08-13,2018-08-12,508838,12328.316,1463.859397,Mixed Breed Medium (23 - 70lb),3.0,...,Hawkey,Melanie,7142 East Bay Blvd,Navarre,FL,32566-9013,HighTenure-HighLR,341.0,0,1

In [12]:
data.to_csv("/home/jash/Desktop/petplan/Profitability.csv")

In [13]:
y=data['L']

In [14]:
data.drop(['LossRatio'],axis=1,inplace=True)

In [15]:
data.drop(['L'],axis=1,inplace=True)

In [16]:
x=data

In [17]:
data['HighTenure-HighLR']=0
data['HighTenure-LowLR']=0
data['LowTenure-HighLR']=0
data['LowTenure-LowLR']=0

In [18]:
data.loc[data['Quadrant']=='HighTenure-HighLR', 'HighTenure-HighLR'] = 1
data.loc[data['Quadrant']=='HighTenure-LowLR', 'HighTenure-LowLR'] = 1
data.loc[data['Quadrant']=='LowTenure-HighLR', 'LowTenure-HighLR'] = 1
data.loc[data['Quadrant']=='LowTenure-LowLR', 'LowTenure-LowLR'] = 1

In [19]:
data.head()

,Duration,PetId,StartDate,EndDate,LastPolicyRef,TotalClaimsAmtPaid,TotalEarnedPremium,BreedName,Currentage,CopayPct,...,CustomerMailingAddr_City,CustomerMailingAddr_StateProvCd,CustomerMailingAddr_PostalCode,Quadrant,claimdurationInception,churn,HighTenure-HighLR,HighTenure-LowLR,LowTenure-HighLR,LowTenure-LowLR
0,1026,US1439036kayla,2015-10-06,2018-11-24,560481,1319.141,2134.399452,Mixed Breed Medium (23 - 70lb),9.0,0.8,...,Elmont,NY,11003-4520,HighTenure-HighLR,952.0,0,1,0,0,0
1,484,US1960128Corbie,2017-03-31,2019-03-30,608993,7568.184,589.292137,Dachshund - long haired,4.0,0.8,...,Tucson,AZ,85715-3343,HighTenure-HighLR,255.0,0,1,0,0,0
2,1025,US1332798Sophie,2015-06-20,2018-04-09,454361,58.460,992.219616,Mixed Breed Small ( up to 22lb ),2.0,0.9,...,Thousand Oaks,CA,91360-4933,HighTenure-LowLR,921.0,1,0,1,0,0
3,528,US1437703Siggy,2015-10-05,2017-03-15,289557,9040.553,554.195726,Labrador Mix,6.0,0.9,...,Houston,TX,77008-2637,LowTenure-HighLR,401.0,1,0,0,1,0
4,1080,US150902Dino,2015-08-13,2018-08-12,508838,12328.316,1463.859397,Mixed Breed Medium (23 - 70lb),3.0,0.9,...,Navarre,FL,32566-9013,HighTenure-HighLR,341.0,0,1,0,0,0

In [20]:
data.drop(['Quadrant'],axis=1,inplace=True)

In [21]:
x.head()
x.to_csv("/home/jash/Desktop/petplan/xonly.csv")

In [22]:
x.drop(['CustomerNumber','PhoneNumber','Surname','GivenName','CustomerMailingAddr_Addr1','CustomerMailingAddr_City','CustomerMailingAddr_StateProvCd',
       'CustomerMailingAddr_PostalCode','PetId','Country'],axis=1,inplace=True)

In [23]:
x.columns

Index([u'Duration', u'StartDate', u'EndDate', u'LastPolicyRef',
       u'TotalClaimsAmtPaid', u'TotalEarnedPremium', u'BreedName',
       u'Currentage', u'CopayPct', u'Deductible', u'PetType', u'PolicyForm',
       u'CarrierCd', u'ClaimNumber', u'ClaimAmount', u'ClaimDetails',
       u'ConditionGrp', u'Claimcodecategory', u'Severity',
       u'claimdurationInception', u'churn\r', u'HighTenure-HighLR',
       u'HighTenure-LowLR', u'LowTenure-HighLR', u'LowTenure-LowLR'],
      dtype='object')

In [24]:
x.head()

,Duration,StartDate,EndDate,LastPolicyRef,TotalClaimsAmtPaid,TotalEarnedPremium,BreedName,Currentage,CopayPct,Deductible,...,ClaimDetails,ConditionGrp,Claimcodecategory,Severity,claimdurationInception,churn,HighTenure-HighLR,HighTenure-LowLR,LowTenure-HighLR,LowTenure-LowLR
0,1026,2015-10-06,2018-11-24,560481,1319.141,2134.399452,Mixed Breed Medium (23 - 70lb),9.0,0.8,400,...,LVJ - hepatopathy,LVJ - hepatopathy,Illness,Curable,952.0,0,1,0,0,0
1,484,2017-03-31,2019-03-30,608993,7568.184,589.292137,Dachshund - long haired,4.0,0.8,250,...,GBC - pancreatitis,Pancreatic Disease,Illness,Curable,255.0,0,1,0,0,0
2,1025,2015-06-20,2018-04-09,454361,58.460,992.219616,Mixed Breed Small ( up to 22lb ),2.0,0.9,300,...,GAA - colitis,Non-specific GI Disease (Vomiting/Diarrhea),Illness,Curable,921.0,1,0,1,0,0
3,528,2015-10-05,2017-03-15,289557,9040.553,554.195726,Labrador Mix,6.0,0.9,200,...,POA - prescription drug poisoning,POA - prescription drug poisoning,Illness,Curable,401.0,1,0,0,1,0
4,1080,2015-08-13,2018-08-12,508838,12328.316,1463.859397,Mixed Breed Medium (23 - 70lb),3.0,0.9,200,...,AA9 - cruciate ligament tear/rupture,Cruciate Injuries,Accident,Non-Curable,341.0,0,1,0,0,0

In [25]:
x.to_csv("/home/jash/Desktop/petplan/xonly_edited.csv")

In [26]:
import numpy as np
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [28]:
X_train.shape

(285355, 25)

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [30]:

clf = RandomForestClassifier(max_depth=2, random_state=0)

In [31]:
import numpy as np
from sklearn.decomposition import PCA

In [32]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [33]:
X_train.head()

,Duration,StartDate,EndDate,LastPolicyRef,TotalClaimsAmtPaid,TotalEarnedPremium,BreedName,Currentage,CopayPct,Deductible,...,ClaimDetails,ConditionGrp,Claimcodecategory,Severity,claimdurationInception,churn,HighTenure-HighLR,HighTenure-LowLR,LowTenure-HighLR,LowTenure-LowLR
257890,0,2017-08-13,2017-08-13,502992,NaN,0.000000,Golden Retriever,1.0,0.8,250,...,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
256568,289,2017-10-12,2018-10-11,533515,NaN,210.019863,Labrador Retriever - Chocolate,1.0,0.9,750,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1
37163,652,2016-10-14,2018-10-13,511935,3400.6,1142.059918,Chihuahua Mix,10.0,0.8,500,...,HTB - mitral valve insufficiency,Cardiac Disease,Illness,Non-Curable,74.0,0,1,0,0,0
135054,30,2016-07-30,2016-08-28,60305,NaN,0.000000,Siberian Husky Mix,7.0,0.8,100,...,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1
296685,30,2015-12-01,2015-12-30,168186,NaN,0.000000,Chihuahua Mix,9.0,0.8,100,...,NaN,NaN,NaN,NaN,NaN,1,0,0,0,1

In [34]:
X_train.columns

Index([u'Duration', u'StartDate', u'EndDate', u'LastPolicyRef',
       u'TotalClaimsAmtPaid', u'TotalEarnedPremium', u'BreedName',
       u'Currentage', u'CopayPct', u'Deductible', u'PetType', u'PolicyForm',
       u'CarrierCd', u'ClaimNumber', u'ClaimAmount', u'ClaimDetails',
       u'ConditionGrp', u'Claimcodecategory', u'Severity',
       u'claimdurationInception', u'churn\r', u'HighTenure-HighLR',
       u'HighTenure-LowLR', u'LowTenure-HighLR', u'LowTenure-LowLR'],
      dtype='object')

In [35]:
import h2o
from h2o.estimators import H2ORandomForestEstimator

ImportError: No module named h2o

In [ ]:
h2o.init()